version: "3.8"

services:
  my-service:
    container_name: my-service
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    volumes:
    - .:/app:rw,delegated
    networks:
    - my_network
    ports:
    - "8085:8085"
    - 2345:2345

networks:
  my_network:
    name: my_network